Fundamental:
  Site:
    templateRootPath: 'resource://Fundamental.Site/Private/Templates/'
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Fundamental.Site:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
      inspector:
        dataTypes:
          'Neos\Media\Domain\Model\ImageInterface':
            editorOptions:
              features:
                resize: TRUE
      navigateComponent:
        nodeTree:
          loadingDepth: 999
        structureTree:
          loadingDepth: 999
    nodeTypes:
      groups:
        socialmedia:
          position: 'end'
          label: Fundamental.Site:Main:socialmedia
        fundamental:
          position: 'end'
          label: Fundamental.Site:Main:fundamental
    fusion:
      autoInclude:
        Fundamental.Site: true